修

diff --git a/system/bin/UNM b/system/bin/UNM
--- a/system/bin/UNM
+++ b/system/bin/UNM
@@ -2,8 +2,6 @@
 
 UnblockNeteaseMusic_path="/data/adb/modules/UnblockNeteaseMusic"
 UnblockNeteaseMusic_link="https://github.com/nondanee/UnblockNeteaseMusic/releases"
-latest_UnblockNeteaseMusic_version=`curl -k -s -I "${UnblockNeteaseMusic_link}/latest" | grep -i location | grep -o "tag.*" | grep -o "v[0-9.]*"`
-download_link="https://codeload.github.com/nondanee/UnblockNeteaseMusic/zip/${latest_UnblockNeteaseMusic_version}"
 sources="kuwo qq xiami baidu joox kugou"
 nodejs=${UnblockNeteaseMusic_path}/node
 appjs=${UnblockNeteaseMusic_path}/UnblockNeteaseMusic/app.js
@@ -11,146 +9,146 @@ pid_file=${UnblockNeteaseMusic_path}/UnblockNeteaseMusic.pid
 port=5464
 portssl=2229
 ports=$port:$portssl
-log=${UnblockNeteaseMusic_path}/日志.log
+log=${UnblockNeteaseMusic_path}/log_server.log
+ip6tables -t nat -S >/dev/null 2>&1 && IPv6support=true || IPv6support=false  # 检查IPv6 nat
 
 check() {
-    boot_start=$(grep boot_start ${UnblockNeteaseMusic_path}/service.sh | head -n 1 | awk -F '=' '{print $2}')
-    if [ -e ${UnblockNeteaseMusic_path}/UnblockNeteaseMusic.pid ];then
-       echo "正在运行"
-    else
-       echo "没有运行"
-    fi
-    if [ $boot_start = "true" ];then
-       echo "开机自启: 开启"
-    else
-       echo "开机自启: 关闭"
-    fi
-    echo "开始打印日志"
-    sleep 4
-    cat $log
+	boot_start=$(grep boot_start ${UnblockNeteaseMusic_path}/service.sh | head -n 1 | awk -F '=' '{print $2}')
+	if [ -e ${UnblockNeteaseMusic_path}/UnblockNeteaseMusic.pid ];then
+		echo "正在运行"
+	else
+		echo "没有运行"
+	fi
+	if [ $boot_start = "true" ];then
+		echo "开机自启: 开启"
+	else
+		echo "开机自启: 关闭"
+	fi
+	echo "开始打印日志"
+	sleep 4
+	cat $log
 }
 
 start() {
-    uid=$(grep -m1 -i "com.netease.cloudmusic" /data/system/packages.list | cut -d' ' -f2)
-    liteuid=$(grep -m1 -i "com.netease.cloudmusic.lite" /data/system/packages.list | cut -d' ' -f2)
-    nohup "$nodejs" "$appjs" -a 0.0.0.0 -p $ports -o $sources -e "http://music.163.com" > "$log" 2>&1 &
-    echo -n $! > ${pid_file}
-    iptables -t nat -A OUTPUT -p tcp -m owner --uid-owner $uid -m tcp --dport 80 -j DNAT --to 127.0.0.1:${port}
-    iptables -t nat -A OUTPUT -p tcp -m owner --uid-owner $uid -m tcp --dport 443 -j DNAT --to 127.0.0.1:${portssl}
-    ip6tables -t nat -A OUTPUT -p tcp -m owner --uid-owner $uid -m tcp --dport 80 -j DNAT --to ::1:${port}
-    ip6tables -t nat -A OUTPUT -p tcp -m owner --uid-owner $uid -m tcp --dport 443 -j DNAT --to ::1:${portssl}
-    if [ $liteuid ];then
-       iptables -t nat -A OUTPUT -p tcp -m owner --uid-owner $liteuid -m tcp --dport 80 -j DNAT --to 127.0.0.1:${port}
-       iptables -t nat -A OUTPUT -p tcp -m owner --uid-owner $liteuid -m tcp --dport 443 -j DNAT --to 127.0.0.1:${portssl}
-       ip6tables -t nat -A OUTPUT -p tcp -m owner --uid-owner $liteuid -m tcp --dport 80 -j DNAT --to ::1:${port}
-       ip6tables -t nat -A OUTPUT -p tcp -m owner --uid-owner $liteuid -m tcp --dport 443 -j DNAT --to ::1:${portssl}
-    fi
-    echo "已开启服务"
+	nohup "$nodejs" "$appjs" -a 0.0.0.0 -p $ports -o $sources -e "http://music.163.com" > "$log" 2>&1 &
+	echo -n $! > ${pid_file}
+	iptrules -A
+	echo "已开启服务"
 }
 
 stop() {
-    uid=$(grep -m1 -i "com.netease.cloudmusic" /data/system/packages.list | cut -d' ' -f2)
-    liteuid=$(grep -m1 -i "com.netease.cloudmusic.lite" /data/system/packages.list | cut -d' ' -f2)
-    kill -9 `cat ${pid_file}` || kill `cat ${pid_file}`
-    iptables -t nat -D OUTPUT -p tcp -m owner --uid-owner $uid -m tcp --dport 80 -j DNAT --to 127.0.0.1:${port}
-    iptables -t nat -D OUTPUT -p tcp -m owner --uid-owner $uid -m tcp --dport 443 -j DNAT --to 127.0.0.1:${portssl}
-    ip6tables -t nat -D OUTPUT -p tcp -m owner --uid-owner $uid -m tcp --dport 80 -j DNAT --to ::1:${port}
-    ip6tables -t nat -D OUTPUT -p tcp -m owner --uid-owner $uid -m tcp --dport 443 -j DNAT --to ::1:${portssl}
-    if [ $liteuid ];then
-       iptables -t nat -D OUTPUT -p tcp -m owner --uid-owner $liteuid -m tcp --dport 80 -j DNAT --to 127.0.0.1:${port}
-       iptables -t nat -D OUTPUT -p tcp -m owner --uid-owner $liteuid -m tcp --dport 443 -j DNAT --to 127.0.0.1:${portssl}
-       ip6tables -t nat -D OUTPUT -p tcp -m owner --uid-owner $liteuid -m tcp --dport 80 -j DNAT --to ::1:${port}
-       ip6tables -t nat -D OUTPUT -p tcp -m owner --uid-owner $liteuid -m tcp --dport 443 -j DNAT --to ::1:${portssl}
-    fi
-    rm -rf ${pid_file}
-    echo "已关闭服务"
+	kill -9 `cat ${pid_file}` || kill `cat ${pid_file}`
+	iptrules -D
+	rm -rf ${pid_file}
+	echo "已关闭服务"
+}
+
+iptrules() {  #处理iptables规则 $1=[-A / -D] 添加或移除
+	local uid; for uid in 'com.netease.cloudmusic' 'com.netease.cloudmusic.lite'
+	do
+		uid=$(grep -m1 -i $uid /data/system/packages.list |cut -d' ' -f2)
+		[ -z "$uid" ] && continue  # 不存在则跳过
+
+		# 加载规则
+		iptables -t nat $1 OUTPUT -p tcp --dport 80 -m owner --uid-owner $uid -j DNAT --to 127.0.0.1:${port}
+		iptables -t nat $1 OUTPUT -p tcp --dport 443 -m owner --uid-owner $uid -j DNAT --to 127.0.0.1:${portssl}
+		if [ $IPv6support == 'true' ];then  # 不支持则封锁
+			ip6tables -t nat $1 OUTPUT -p tcp -m owner --uid-owner $uid -m tcp --dport 80 -j DNAT --to ::1:${port}
+			ip6tables -t nat $1 OUTPUT -p tcp -m owner --uid-owner $uid -m tcp --dport 443 -j DNAT --to ::1:${portssl}
+		else
+			ip6tables -t filter $1 OUTPUT -p tcp -m owner --uid-owner $uid -m multiport --destination-port 80,443 -j DROP
+		fi
+	done
 }
 
 boot_start_on() {
-    sed -i "s/boot_start=false/boot_start=true/g" ${UnblockNeteaseMusic_path}/service.sh
-    boot_start=$(grep boot_start ${UnblockNeteaseMusic_path}/service.sh | head -n 1 | awk -F '=' '{print $2}')
-    echo "开机自启: 开启"
+	sed -i "s/boot_start=false/boot_start=true/g" ${UnblockNeteaseMusic_path}/service.sh
+	boot_start=$(grep boot_start ${UnblockNeteaseMusic_path}/service.sh | head -n 1 | awk -F '=' '{print $2}')
+	echo "开机自启: 开启"
 }
 
 boot_start_off() {
-    sed -i "s/boot_start=true/boot_start=false/g" ${UnblockNeteaseMusic_path}/service.sh
-    boot_start=$(grep boot_start ${UnblockNeteaseMusic_path}/service.sh | head -n 1 | awk -F '=' '{print $2}')
-    echo "开机自启: 关闭"
+	sed -i "s/boot_start=true/boot_start=false/g" ${UnblockNeteaseMusic_path}/service.sh
+	boot_start=$(grep boot_start ${UnblockNeteaseMusic_path}/service.sh | head -n 1 | awk -F '=' '{print $2}')
+	echo "开机自启: 关闭"
 }
 
 update() {
-    if [ -e ${UnblockNeteaseMusic_path}/UnblockNeteaseMusic.pid ];then
-       stop
-    fi
-    echo "开始更新"
-    if [ "${latest_UnblockNeteaseMusic_version}" = "" ] ; then
-       echo "Error: 获取链接失败" 
-       exit 1
-    fi
-    curl "${download_link}" -k -L -o "${UnblockNeteaseMusic_path}/UnblockNeteaseMusic.zip" >&2
-    if [ "$?" != "0" ] ; then
-       echo "Error: 下载UnblockNeteaseMusic失败"
-       exit 1
-    fi
-    echo ${latest_UnblockNeteaseMusic_version} >> ${UnblockNeteaseMusic_path}/version
-    sed -i "s/v//g" ${UnblockNeteaseMusic_path}/version
-    version=$(cat ${UnblockNeteaseMusic_path}/version)
-    unzip -o "${UnblockNeteaseMusic_path}/UnblockNeteaseMusic.zip" -d ${UnblockNeteaseMusic_path} >&2
-    rm -rf ${UnblockNeteaseMusic_path}/UnblockNeteaseMusic
-    mv "${UnblockNeteaseMusic_path}/UnblockNeteaseMusic-${version}" "${UnblockNeteaseMusic_path}/UnblockNeteaseMusic"
-    rm -rf ${UnblockNeteaseMusic_path}/UnblockNeteaseMusic.zip
-    rm -rf ${UnblockNeteaseMusic_path}/version
-    
-    rm -rf ${UnblockNeteaseMusic_path}/module.prop
-    touch ${UnblockNeteaseMusic_path}/module.prop
-    echo "id=UnblockNeteaseMusic" > ${UnblockNeteaseMusic_path}/module.prop
-    echo "name=UnblockNeteaseMusic for Magisk" >> ${UnblockNeteaseMusic_path}/module.prop
-    echo "version=${latest_UnblockNeteaseMusic_version}" >> ${UnblockNeteaseMusic_path}/module.prop
-    echo "versionCode=$(date +%Y%m%d)" >> ${UnblockNeteaseMusic_path}/module.prop
-    echo "author=依然的爱" >> ${UnblockNeteaseMusic_path}/module.prop
-    echo "description=网易云音乐解锁变灰，服务状态控制请在在终端以su权限输入UnblockNeteaseMusic以控制，默认开机自启" >> ${UnblockNeteaseMusic_path}/module.prop
-    echo "更新完毕"
+	latest_UnblockNeteaseMusic_version=`curl -k -s -I "${UnblockNeteaseMusic_link}/latest" | grep -i location | grep -o "tag.*" | grep -o "v[0-9.]*"`
+	download_link="https://codeload.github.com/nondanee/UnblockNeteaseMusic/zip/${latest_UnblockNeteaseMusic_version}"
+
+	if [ -e ${UnblockNeteaseMusic_path}/UnblockNeteaseMusic.pid ];then
+		stop
+	fi
+	echo "开始更新"
+	if [ "${latest_UnblockNeteaseMusic_version}" = "" ] ; then
+		echo "Error: 获取链接失败" 
+		exit 1
+	fi
+	curl "${download_link}" -k -L -o "${UnblockNeteaseMusic_path}/UnblockNeteaseMusic.zip" >&2
+	if [ "$?" != "0" ] ; then
+		echo "Error: 下载UnblockNeteaseMusic失败"
+		exit 1
+	fi
+	echo ${latest_UnblockNeteaseMusic_version} >> ${UnblockNeteaseMusic_path}/version
+	sed -i "s/v//g" ${UnblockNeteaseMusic_path}/version
+	version=$(cat ${UnblockNeteaseMusic_path}/version)
+	unzip -o "${UnblockNeteaseMusic_path}/UnblockNeteaseMusic.zip" -d ${UnblockNeteaseMusic_path} >&2
+	rm -rf ${UnblockNeteaseMusic_path}/UnblockNeteaseMusic
+	mv "${UnblockNeteaseMusic_path}/UnblockNeteaseMusic-${version}" "${UnblockNeteaseMusic_path}/UnblockNeteaseMusic"
+	rm -rf ${UnblockNeteaseMusic_path}/UnblockNeteaseMusic.zip
+	rm -rf ${UnblockNeteaseMusic_path}/version
+
+	rm -rf ${UnblockNeteaseMusic_path}/module.prop
+	touch ${UnblockNeteaseMusic_path}/module.prop
+	echo "id=UnblockNeteaseMusic" > ${UnblockNeteaseMusic_path}/module.prop
+	echo "name=UnblockNeteaseMusic for Magisk" >> ${UnblockNeteaseMusic_path}/module.prop
+	echo "version=${latest_UnblockNeteaseMusic_version}" >> ${UnblockNeteaseMusic_path}/module.prop
+	echo "versionCode=$(date +%Y%m%d)" >> ${UnblockNeteaseMusic_path}/module.prop
+	echo "author=依然的爱" >> ${UnblockNeteaseMusic_path}/module.prop
+	echo "description=网易云音乐解锁变灰，服务状态控制请在在终端以su权限输入UnblockNeteaseMusic以控制，默认开机自启" >> ${UnblockNeteaseMusic_path}/module.prop
+	echo "更新完毕"
 }
 
 -help() {
-    echo "$0"
-    echo "-help    帮助"
-    echo "check    检查运行状态"
-    echo "start | stop | restart    开启服务|关闭服务|重启服务"
-    echo "boot_start_on    开启开机自启"
-    echo "boot_start_off    关闭启开机自启"
-    echo "update    更新UnblockNeteaseMusic脚本"
+	echo "$0"
+	echo "-help	帮助"
+	echo "check	检查运行状态"
+	echo "start | stop | restart	开启服务|关闭服务|重启服务"
+	echo "boot_start_on	开启开机自启"
+	echo "boot_start_off	关闭启开机自启"
+	echo "update	更新UnblockNeteaseMusic脚本"
 }
 
 case "$1" in
   check)
-    check
-    ;;
+	check
+	;;
   start)
-    start
-    ;;
+	start
+	;;
   stop)
-    stop
-    ;;
+	stop
+	;;
   restart)
-    stop
-    sleep 3
-    start
-    ;;
+	stop
+	sleep 3
+	start
+	;;
   boot_start_on)
-    boot_start_on
-    ;;
+	boot_start_on
+	;;
   boot_start_off)
-    boot_start_off
-    ;;
+	boot_start_off
+	;;
 #  update)
-#    update
-#    ;;
+#	update
+#	;;
   -help)
-    -help
-    ;;
+	-help
+	;;
   *)
-    echo "Error : Not command"
-    -help
-    ;;
+	echo "Error : Not command"
+	-help
+	;;
 esac
